\ TCOMDBG-ED.fth — SZ-EDITOR bindings for TCOMDBG
\
\ Public domain. Load AFTER Editor/SZ-EDITOR.fth and TCOMDBG.fth.
\ Installs: open TSRC-CUR-PATH, quiet console, highlight current word,
\ Files-column stack pane via SZ-SIDE-HOOK.

TCOM-ANEW TCOMDBG-ED

FORTH DEFINITIONS
DECIMAL

ALSO EDITOR

: TDBG-ED-OPEN  ( -- )
  [DEFINED] TSRC-CUR-PATH [IF]
    TSRC-CUR-PATH COUNT DUP IF
      SZ-LOAD DROP
      -1 TDBG-QUIET !
    ELSE  2DROP  THEN
  [THEN]
  ;

: TDBG-ED-HIGHLIGHT  ( -- )
  SZ-EDITOR-ACTIVE @ 0= IF EXIT THEN
  DBG-PC@ DBG-SYM@
  DUP 0= IF  2DROP EXIT  THEN
  DUP 63 MIN
  DUP SZ-TOKEN C!
  SZ-TOKEN 1+ SWAP CMOVE
  SZ-TBUF SZ-SEARCH-FWD
  DUP 0= IF  DROP EXIT  THEN
  DUP SZ-TOKEN C@ +
  SZ-SET-SEL
  DUP SZ-CUR !
  SZ-ENSURE-VISIBLE
  ;

: TDBG-ED-PAINT-SIDE  ( -- )
  SZ-EDITOR-ACTIVE @ 0= IF EXIT THEN
  TDBG-SESSION @ 0= IF EXIT THEN
  SZ-TEXT-TOP
  BEGIN  DUP SZ-TEXT-BOT @ > 0= WHILE
    SZ-SIDE-LEFT OVER AT-XY
    SZ-SIDE-WIDTH 0 DO  BL EMIT  LOOP
    1+
  REPEAT DROP
  DBG-PC@ DBG-SYM@ TDBG-NAME PLACE
  SZ-SIDE-LEFT SZ-TEXT-TOP AT-XY
  S" >> " TYPE  TDBG-NAME COUNT TYPE
  TDBG-SBUF 16 DBG-STACK >R
  SZ-SIDE-LEFT SZ-TEXT-TOP 1+ AT-XY
  S" Data " TYPE  R@ .
  SZ-TEXT-TOP 2 +
  R> 0 ?DO
    DUP SZ-TEXT-BOT @ > IF  DROP LEAVE  THEN
    SZ-SIDE-LEFT OVER AT-XY
    I 0= IF  S" T " TYPE  ELSE  S"   " TYPE  THEN
    TDBG-SBUF I CELLS + @ .
    1+
  LOOP
  DUP >R
  SZ-SIDE-LEFT R@ AT-XY  S" Return " TYPE
  TDBG-RBUF 16 DBG-RSTACK
  R> 1+ SWAP 0 ?DO
    DUP SZ-TEXT-BOT @ > IF  DROP LEAVE  THEN
    SZ-SIDE-LEFT OVER AT-XY
    I TDBG-LAB 31 DBG-RLABEL
    TDBG-LAB COUNT TYPE
    1+
  LOOP DROP
  TERMINAL-REFRESH
  ;

: TDBG-ED-SIDE-HOOK  ( -- )  TDBG-ED-PAINT-SIDE ;

: TDBG-ED-PAUSE  ( -- )
  SZ-EDITOR-ACTIVE @ IF
    -1 TDBG-QUIET !
    TDBG-ED-HIGHLIGHT
    SZ-REDRAW
    TDBG-ED-PAINT-SIDE
  ELSE
    0 TDBG-QUIET !
    TDBG-UI-PAUSE-D
  THEN
  ;

: TDBG-ED-DONE  ( -- )
  0 TDBG-QUIET !
  0 SZ-SEL-OK !
  SZ-EDITOR-ACTIVE @ IF  SZ-REDRAW  THEN
  ;

: NOOP  ( -- )  ;

' TDBG-ED-OPEN  IS TDBG-UI-OPEN
' TDBG-ED-PAUSE IS TDBG-UI-PAUSE
' TDBG-ED-DONE  IS TDBG-UI-DONE

[DEFINED] SZ-SIDE-HOOK [IF]
  ' TDBG-ED-SIDE-HOOK IS SZ-SIDE-HOOK
[THEN]

PREVIOUS

FORTH DEFINITIONS
S" TCOMDBG-ED loaded (editor highlight + quiet + side pane)." TYPE CR
