\ TARGETARM64.fth — Load 64TCOM ARM64 configuration
\
\ Public domain.
\ Load from 64TCOMARM64/:
\   FLOAD TARGETARM64.fth
\
\ Then:  .ARM64  ARM64-DEMO  FWD-ARM64
\
\ Optional: FILE-ECHO ON  before FLOAD for a full line trace.

FORTH DEFINITIONS DECIMAL

[UNDEFINED] TCOM-ANEW [IF]
: TCOM-ANEW  ( "<spaces>name" -- )
  >IN @
  BL WORD FIND IF
    DROP OVER >IN ! FORGET
  ELSE
    DROP
  THEN
  >IN !  CREATE
  ;
[THEN]

TCOM-ANEW TARGETARM64

FORTH DEFINITIONS
DECIMAL

FILE-ECHO OFF

S" [TARGETARM64] loading..." TYPE CR
INCLUDE ../64TCOMSRC/64HOST.fth
INCLUDE ../64TCOMSRC/64DIR.fth
INCLUDE ASMARM64.fth
INCLUDE OPTARM64.fth
INCLUDE LIBARM64.fth
INCLUDE SIMARM64.fth
INCLUDE NATARM64.fth
INCLUDE MACHOARM64.fth
\ Generic .tfth loader (compiler) — after pack hooks/prims exist
INCLUDE ../64TCOMSRC/64SRC.fth

\ Pack wrapper: .tfth → image → Mach-O entry MAIN (after 64SRC is loaded)
: TSRC-BUILD  ( ca u -- )
  TARGET-INIT
  LL-INIT
  TSRC-INCLUDE
  ARM64-FINISH
  S" MAIN" MACHO-ENTRY-SET
  SAVE-MACHO-FILE
  ;

TCOM-ORDER
TCOM-WARN-ON

: (A64-CLEAR-STACK)  ( -- )
  BEGIN DEPTH WHILE DROP REPEAT
  ;
(A64-CLEAR-STACK)

S" 64TCOM ARM64 ready — " TYPE TVERSION CR
S" HERE-T=" TYPE HERE-T . S"  LIB-CODE-END=" TYPE LIB-CODE-END @ . CR
S" Native: .RUN-ANS-N   Standalone: SAVE-MACHO-FILE (see .MACHOARM64)" TYPE CR
S" Try: SRC-DEMO  (or path TSRC-BUILD for .tfth → MAIN Mach-O)" TYPE CR
