\ 64SRC.fth — Generic restricted target-source loader (pack-independent)
\
\ Public domain. Requires 64HOST + 64DIR.
\ Lives in 64TCOMSRC (compiler), NOT in a target pack.
\
\ Pack must provide before TSRC-INCLUDE (ARM64 does):
\   TIF TELSE TTHEN TBEGIN TUNTIL TAGAIN TWHILE TREPEAT
\   G@ G!
\   Library: PLUS# MINUS# DUP# DROP# SWAP# OVER# FETCH# STORE#
\
\ Dialect (.tfth):
\   \ comment   ( comment )
\   VARIABLE name
\   : name … ;
\   decimal | $hex
\   IF ELSE THEN BEGIN UNTIL AGAIN WHILE REPEAT
\   @ ! + - DUP DROP SWAP OVER
\   other names → SYM-COMPILE-REF (call or data addr)
\
\ API (caller does TARGET-INIT / finish):
\   c-addr u TSRC-INCLUDE
\   TSRC-INCLUDE" path.tfth"

TCOM-ANEW 64SRC

FORTH DEFINITIONS
DECIMAL

8192 CONSTANT /TSRC-BUF
CREATE TSRC-BUF  /TSRC-BUF ALLOT
VARIABLE TSRC-LEN
VARIABLE TSRC-I
VARIABLE TSRC-LINE
CREATE TSRC-WORD  128 ALLOT
VARIABLE TSRC-IN-COLON
VARIABLE TSRC-ACC
VARIABLE TSRC-BASE
VARIABLE TSRC-OK
VARIABLE TSRC-FID

: TSRC-ERR  ( ca u -- )
  S" TSRC line " TYPE TSRC-LINE @ 0 .R S" : " TYPE TYPE CR
  TCOM-ABORT
  ;

: TSRC-EOF?  ( -- f )  TSRC-I @ TSRC-LEN @ U>= ;

: TSRC-PEEK  ( -- c | -1 )
  TSRC-EOF? IF  -1 EXIT  THEN
  TSRC-BUF TSRC-I @ + C@
  ;

: TSRC-GETC  ( -- c | -1 )
  TSRC-PEEK DUP 0< IF EXIT THEN
  TSRC-I @ 1+ TSRC-I !
  DUP 10 = IF  1 TSRC-LINE +!  THEN
  ;

: TSRC-SKIP-WS  ( -- )
  BEGIN
    TSRC-PEEK DUP 0< IF  DROP EXIT  THEN
    DUP BL > IF  DROP EXIT  THEN
    DROP TSRC-GETC DROP
  AGAIN
  ;

: TSRC-SKIP-LINE  ( -- )
  BEGIN
    TSRC-GETC DUP 0< IF  DROP EXIT  THEN
    10 = IF EXIT THEN
  AGAIN
  ;

: TSRC-SKIP-PAREN  ( -- )
  BEGIN
    TSRC-GETC DUP 0< IF  DROP S" unclosed (" TSRC-ERR  THEN
    [CHAR] ) = IF EXIT THEN
  AGAIN
  ;

: TSRC-TOKEN  ( -- ca u )
  TSRC-SKIP-WS
  TSRC-EOF? IF  TSRC-WORD 0 EXIT  THEN
  TSRC-PEEK [CHAR] \ = IF
    TSRC-GETC DROP TSRC-SKIP-LINE RECURSE EXIT
  THEN
  TSRC-PEEK [CHAR] ( = IF
    TSRC-GETC DROP TSRC-SKIP-PAREN RECURSE EXIT
  THEN
  0 TSRC-WORD C!
  BEGIN
    TSRC-PEEK DUP 0< IF  DROP TSRC-WORD COUNT EXIT  THEN
    DUP BL <= IF  DROP TSRC-WORD COUNT EXIT  THEN
    TSRC-GETC
    TSRC-WORD C@ 126 U< IF
      TSRC-WORD COUNT + C!
      TSRC-WORD C@ 1+ TSRC-WORD C!
    ELSE DROP THEN
  AGAIN
  ;

: TSRC-EQ  ( ca1 u1 ca2 u2 -- f )
  ROT 2DUP <> IF  2DROP 2DROP FALSE EXIT  THEN
  DROP
  0 DO
    OVER C@ OVER C@ <> IF  2DROP UNLOOP FALSE EXIT  THEN
    SWAP 1+ SWAP 1+
  LOOP
  2DROP TRUE
  ;

: TSRC-DIGIT  ( c base -- n | -1 )
  >R
  DUP [CHAR] 0 [CHAR] 9 1+ WITHIN IF
    [CHAR] 0 - DUP R@ < IF  R> DROP EXIT  THEN
    DROP R> DROP -1 EXIT
  THEN
  DUP [CHAR] A [CHAR] F 1+ WITHIN IF
    [CHAR] A - 10 + DUP R@ < IF  R> DROP EXIT  THEN
    DROP R> DROP -1 EXIT
  THEN
  DUP [CHAR] a [CHAR] f 1+ WITHIN IF
    [CHAR] a - 10 + DUP R@ < IF  R> DROP EXIT  THEN
    DROP R> DROP -1 EXIT
  THEN
  DROP R> DROP -1
  ;

\ ( ca u -- n true | false )  always consumes ca u
: TSRC->NUMBER  ( ca u -- n true | false )
  DUP 0= IF  2DROP FALSE EXIT  THEN
  OVER C@ [CHAR] $ = IF
    1 /STRING DUP 0= IF  2DROP FALSE EXIT  THEN
    16
  ELSE  10  THEN  TSRC-BASE !
  0 TSRC-ACC !  FALSE TSRC-OK !
  BEGIN DUP WHILE
    OVER C@ TSRC-BASE @ TSRC-DIGIT
    DUP 0< IF  DROP 2DROP FALSE EXIT  THEN
    TSRC-ACC @ TSRC-BASE @ * + TSRC-ACC !
    TRUE TSRC-OK !
    1 /STRING
  REPEAT
  2DROP
  TSRC-OK @ 0= IF  FALSE EXIT  THEN
  TSRC-ACC @ TRUE
  ;

: TSRC-COLON  ( ca u -- )
  \ Name already on stack — do NOT use (T-COOKIE)/CREATE (would BL WORD from TIB).
  TSRC-IN-COLON @ IF  2DROP S" nested :" TSRC-ERR  THEN
  START-T:
  HERE-T M-TMP !
  ENTRY-LANDING
  2DUP PAD 2 CELLS + PLACE
  PAD 2 CELLS + COMP-HEADER
  SYM-TARGET M-TMP @ SYM-DEFINE DROP   \ ( ca u type addr -- ix )
  TRUE TO ?INTERPRETIVE
  TRUE TSRC-IN-COLON !
  ;

: TSRC-SEMI  ( -- )
  TSRC-IN-COLON @ 0= IF  S" ; outside :" TSRC-ERR  THEN
  END-T:
  FALSE TO ?INTERPRETIVE
  FALSE TSRC-IN-COLON !
  ;

: TSRC-VARIABLE  ( ca u -- )
  \ ( ca u ) name — allocate one cell in target DATA, SYM-DATA with host addr
  TSRC-IN-COLON @ IF  2DROP S" VARIABLE inside :" TSRC-ERR  THEN
  CELL-ALIGN-D
  HERE-D                       ( ca u daddr )
  0 OVER !-D                   \ zero cell
  T-CELL ALLOT-D
  DTHERE                       ( ca u host )
  >R  SYM-DATA R> SYM-ADD DROP
  ;

: TSRC-HOST-EXEC  ( ca u -- )
  DUP PAD C!
  PAD 1+ SWAP MOVE
  PAD FIND IF
    EXECUTE
  ELSE
    COUNT TYPE S"  (host) not found — load target pack first" TSRC-ERR
  THEN
  ;

: TSRC-LIB-CALL  ( ca u -- )
  2DUP SYM-FIND IF
    NIP NIP SYM-ADDR@ COMP-CALL
  ELSE
    TYPE S"  prim missing" TSRC-ERR
  THEN
  ;

: TSRC-PRIM?  ( ca u -- f )
  2DUP S" +" TSRC-EQ IF  2DROP S" PLUS#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" -" TSRC-EQ IF  2DROP S" MINUS#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" DUP" TSRC-EQ IF  2DROP S" DUP#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" DROP" TSRC-EQ IF  2DROP S" DROP#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" SWAP" TSRC-EQ IF  2DROP S" SWAP#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" OVER" TSRC-EQ IF  2DROP S" OVER#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" @" TSRC-EQ IF  2DROP S" G@" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" !" TSRC-EQ IF  2DROP S" G!" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DROP FALSE
  ;

: TSRC-CTRL?  ( ca u -- f )
  2DUP S" IF" TSRC-EQ IF  2DROP S" TIF" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" ELSE" TSRC-EQ IF  2DROP S" TELSE" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" THEN" TSRC-EQ IF  2DROP S" TTHEN" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" BEGIN" TSRC-EQ IF  2DROP S" TBEGIN" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" UNTIL" TSRC-EQ IF  2DROP S" TUNTIL" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" AGAIN" TSRC-EQ IF  2DROP S" TAGAIN" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" WHILE" TSRC-EQ IF  2DROP S" TWHILE" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" REPEAT" TSRC-EQ IF  2DROP S" TREPEAT" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DROP FALSE
  ;

: TSRC-DISPATCH  ( ca u -- )
  DUP 0= IF  2DROP EXIT  THEN

  2DUP S" VARIABLE" TSRC-EQ IF
    2DROP TSRC-TOKEN DUP 0= IF  2DROP S" VARIABLE needs a name" TSRC-ERR  THEN
    TSRC-VARIABLE EXIT
  THEN
  2DUP S" :" TSRC-EQ IF
    2DROP TSRC-TOKEN DUP 0= IF  2DROP S" : needs a name" TSRC-ERR  THEN
    TSRC-COLON EXIT
  THEN
  2DUP S" ;" TSRC-EQ IF  2DROP TSRC-SEMI EXIT  THEN
  2DUP TSRC-CTRL? IF  EXIT  THEN

  TSRC-IN-COLON @ 0= IF
    TYPE S"  at top level (only VARIABLE and : … ;)" TSRC-ERR
  THEN

  2DUP TSRC-PRIM? IF  EXIT  THEN

  \ Number: try without keeping ca u on success
  OVER C@ DUP [CHAR] $ = SWAP DUP [CHAR] 0 [CHAR] 9 1+ WITHIN OR IF
    DROP
    2DUP TSRC->NUMBER IF  >R 2DROP R> G, EXIT  THEN
  ELSE DROP THEN

  2DUP SYM-FIND IF
    NIP NIP SYM-COMPILE-REF
  ELSE
    TYPE S"  ?" TSRC-ERR
  THEN
  ;

: TSRC-LOAD-FILE  ( ca u -- )
  R/O OPEN-FILE IF
    DROP TYPE S" : can't open source" TSRC-ERR
  THEN
  TSRC-FID !
  0 TSRC-LEN !
  BEGIN
    TSRC-BUF TSRC-LEN @ +
    /TSRC-BUF TSRC-LEN @ - 1-
    TSRC-FID @ READ-FILE
    IF
      TSRC-FID @ CLOSE-FILE DROP
      S" read error" TSRC-ERR
    THEN
    DUP 0= IF
      DROP TSRC-FID @ CLOSE-FILE DROP EXIT
    THEN
    TSRC-LEN @ + DUP /TSRC-BUF 1- > IF
      DROP TSRC-FID @ CLOSE-FILE DROP
      S" file too large for TSRC buffer (8KiB)" TSRC-ERR
    THEN
    TSRC-LEN !
  AGAIN
  ;

: TSRC-RUN  ( -- )
  0 TSRC-I !
  1 TSRC-LINE !
  FALSE TSRC-IN-COLON !
  BEGIN
    TSRC-TOKEN DUP
  WHILE
    TSRC-DISPATCH
  REPEAT
  2DROP
  TSRC-IN-COLON @ IF  S" unclosed : at EOF" TSRC-ERR  THEN
  ;

: TSRC-INCLUDE  ( ca u -- )
  ?QUIET 0= IF  2DUP TYPE S"  (TSRC)" TYPE CR  THEN
  TSRC-LOAD-FILE
  TSRC-RUN
  ;

: TSRC-INCLUDE"  ( -- )
  [CHAR] " PARSE TSRC-INCLUDE
  ;

: .64SRC  ( -- )
  S" 64SRC — restricted .tfth loader (compiler, pack-independent)" TYPE CR
  S"   c-addr u TSRC-INCLUDE" TYPE CR
  S"   Needs pack: TIF TELSE TTHEN … G@ G! prims" TYPE CR
  ;

FORTH DEFINITIONS
S" 64SRC loaded (TSRC-INCLUDE)." TYPE CR
