\ 64SRC.fth — Generic restricted target-source loader (pack-independent)
\
\ Public domain. Requires 64HOST + 64DIR.
\ Lives in 64TCOMSRC (compiler), NOT in a target pack.
\
\ Pack must provide before TSRC-INCLUDE (ARM64 does):
\   TIF TELSE TTHEN TBEGIN TUNTIL TAGAIN TWHILE TREPEAT
\   G@ G!  COMP-DATA-ADDR  (for VARIABLE and S" strings)
\   Library: PLUS# MINUS# DUP# DROP# SWAP# OVER# FETCH# STORE# TYPE# ARG##
\   Host compile words: ARGCOUNT ARG1 ARG2 ARG#
\
\ Dialect (.fth) — extension distinguishes target source from host .fth:
\   \ comment          (to end of line)
\   ( comment )        (paren, may span lines)
\   \\ … {             (multi-line block; opener is two backslashes)
\   } … {              (alias for the same multi-line block)
\   VARIABLE name   CREATE name   n CONSTANT name   n VALUE name
\   : name … ;   :NONAME … ;   RECURSE   IMMEDIATE
\   CREATE … DOES> … ;   : name CREATE … DOES> … ;
\   [ host-expr ] LITERAL   POSTPONE name
\   : name … ;
\   FLOAD path.fth   |  INCLUDE path.fth   (top-level; nested .fth)
\   decimal | $hex
\   IF ELSE THEN BEGIN UNTIL AGAIN WHILE REPEAT
\   @ ! + - DUP DROP SWAP OVER
\   S-quote text quote   TYPE   dot-quote text quote  (Layer 2 print)
\   ARGCOUNT ARG1 ARG2 ARG#   (Layer 2 CLI args; 1-based user argv)
\   0= = < >   ROT NIP 2DUP   EMIT CR SPACE .   S>N
\   CHAR c   [CHAR] c   (compile ASCII code of first char of next word)
\   other names → SYM-COMPILE-REF (call or data addr)
\
\ API (caller does TARGET-INIT / finish):
\   c-addr u TSRC-INCLUDE
\   TSRC-INCLUDE" path.fth"
\
\ FLOAD/INCLUDE in a .fth loads another restricted target file (not host FLOAD).
\ Relative paths are resolved against the including file's directory.

TCOM-ANEW 64SRC

FORTH DEFINITIONS
DECIMAL

\ Source buffer: ALLOCATE/RESIZE heap, not a fixed dictionary allot.
\ Default floor 64 KiB; TSRC-LOAD-FILE grows to FILE-SIZE (and more while reading).
65536 CONSTANT /TSRC-BUF-MIN
16777216 CONSTANT /TSRC-BUF-MAX          \ 16 MiB sanity cap
VARIABLE TSRC-BUF-ADDR                   \ 0 until TSRC-BUF-BOOT
VARIABLE TSRC-BUF-CAP                    \ current capacity (bytes)
VARIABLE TSRC-NEED                       \ expected size from FILE-SIZE (-1 = unknown)
0 TSRC-BUF-ADDR !
0 TSRC-BUF-CAP !

: TSRC-BUF   ( -- addr )  TSRC-BUF-ADDR @ ;
: /TSRC-BUF  ( -- n )     TSRC-BUF-CAP @ ;

VARIABLE TSRC-LEN
VARIABLE TSRC-I
VARIABLE TSRC-LINE
CREATE TSRC-WORD  128 ALLOT
VARIABLE TSRC-IN-COLON
VARIABLE TSRC-TOK-AT                 \ TSRC-I at start of current token
VARIABLE TSRC-LAST                   \ last defined symbol ix (-1 none)
VARIABLE TSRC-BODY0                  \ source offset of current colon body
VARIABLE TSRC-BODY1                  \ source offset of terminating ;
VARIABLE TSRC-NONAME                 \ :NONAME in progress
VARIABLE TSRC-BRACKET                \ inside [ … ]
VARIABLE TSRC-DEFINER                \ current : is CREATE … DOES>
VARIABLE TSRC-SKIP-CT                \ skip compile-time part of definer
VARIABLE TSRC-IN-DOES                \ top-level DOES> … ;
VARIABLE TSRC-CT0                    \ compile-time source start (offset)
VARIABLE TSRC-CT1                    \ compile-time source end (offset)
VARIABLE TSRC-DOES-XT                \ taddr of DOES> body
-1 TSRC-LAST !
DEFER TSRC-DISPATCH
8192 CONSTANT /TSRC-CTPOOL
CREATE TSRC-CTPOOL  /TSRC-CTPOOL ALLOT
VARIABLE TSRC-CTP
0 TSRC-CTP !
VARIABLE TSRC-ACC
VARIABLE TSRC-BASE
VARIABLE TSRC-OK
VARIABLE TSRC-FID

\ Current source path / directory (for relative FLOAD)
CREATE TSRC-CUR-PATH  256 ALLOT
CREATE TSRC-CUR-DIR   256 ALLOT
CREATE TSRC-RESOLVED  256 ALLOT
34 CONSTANT TSRC-QUOT-CH

\ Nesting: save parent buffer + scan state
\ Per-level heap slots (not a fixed stride arena) so the main buffer can grow.
8 CONSTANT #TSRC-NEST
VARIABLE TSRC-DEPTH
0 TSRC-DEPTH !
CREATE TSRC-NEST-LEN   #TSRC-NEST CELLS ALLOT
CREATE TSRC-NEST-I     #TSRC-NEST CELLS ALLOT
CREATE TSRC-NEST-LINE  #TSRC-NEST CELLS ALLOT
CREATE TSRC-NEST-PATH  #TSRC-NEST 256 * ALLOT
CREATE TSRC-NEST-DIR   #TSRC-NEST 256 * ALLOT
CREATE TSRC-NEST-BA    #TSRC-NEST CELLS ALLOT   \ buffer addr per level (0 = none)
CREATE TSRC-NEST-BC    #TSRC-NEST CELLS ALLOT   \ capacity per level

DEFER TSRC-DO-FLOAD
: (TSRC-FLOAD-STUB)  ( -- )  S" TSRC-DO-FLOAD not set" TYPE CR TCOM-ABORT ;
' (TSRC-FLOAD-STUB) IS TSRC-DO-FLOAD

: TSRC-ERR  ( ca u -- )
  S" TSRC line " TYPE TSRC-LINE @ 0 .R S" : " TYPE TYPE CR
  TCOM-ABORT
  ;

\ ( need -- ) ensure main buffer capacity >= need (and >= MIN); abort on failure
: TSRC-ENSURE-CAP  ( need -- )
  DUP 0< IF  DROP S" TSRC: negative buffer size" TSRC-ERR  THEN
  /TSRC-BUF-MIN MAX
  DUP /TSRC-BUF-MAX U> IF
    DROP S" TSRC: file exceeds 16 MiB buffer cap" TSRC-ERR
  THEN
  DUP TSRC-BUF-CAP @ U> 0= IF  DROP EXIT  THEN
  TSRC-BUF-ADDR @ 0= IF
    DUP ALLOCATE IF
      2DROP S" TSRC: ALLOCATE failed" TSRC-ERR
    THEN
    TSRC-BUF-ADDR !
    TSRC-BUF-CAP !
    EXIT
  THEN
  TSRC-BUF-ADDR @ OVER RESIZE IF
    2DROP S" TSRC: RESIZE failed" TSRC-ERR
  THEN
  TSRC-BUF-ADDR !
  TSRC-BUF-CAP !
  ;

\ Double capacity (used when reading past FILE-SIZE or size unknown)
: TSRC-GROW  ( -- )
  /TSRC-BUF DUP IF 2* ELSE DROP /TSRC-BUF-MIN THEN
  TSRC-ENSURE-CAP
  ;

\ ( idx need -- ) ensure nest slot idx can hold need bytes
: TSRC-NEST-ENSURE  ( idx need -- )
  SWAP >R                                    \ need | R: idx
  DUP R@ CELLS TSRC-NEST-BC + @ U> 0= IF
    DROP R> DROP EXIT
  THEN
  R@ CELLS TSRC-NEST-BA + @ 0= IF
    DUP ALLOCATE IF
      2DROP R> DROP S" TSRC: nest ALLOCATE failed" TSRC-ERR
    THEN
    R@ CELLS TSRC-NEST-BA + !
    R> CELLS TSRC-NEST-BC + !
    EXIT
  THEN
  R@ CELLS TSRC-NEST-BA + @ OVER RESIZE IF
    2DROP R> DROP S" TSRC: nest RESIZE failed" TSRC-ERR
  THEN
  R@ CELLS TSRC-NEST-BA + !
  R> CELLS TSRC-NEST-BC + !
  ;

: TSRC-BUF-BOOT  ( -- )
  0 TSRC-BUF-ADDR !
  0 TSRC-BUF-CAP !
  /TSRC-BUF-MIN TSRC-ENSURE-CAP
  #TSRC-NEST 0 DO
    0 I CELLS TSRC-NEST-BA + !
    0 I CELLS TSRC-NEST-BC + !
  LOOP
  ;

TSRC-BUF-BOOT

: TSRC-EOF?  ( -- f )  TSRC-I @ TSRC-LEN @ U>= ;

: TSRC-PEEK  ( -- c | -1 )
  TSRC-EOF? IF  -1 EXIT  THEN
  TSRC-BUF TSRC-I @ + C@
  ;

: TSRC-GETC  ( -- c | -1 )
  TSRC-PEEK DUP 0< IF EXIT THEN
  TSRC-I @ 1+ TSRC-I !
  DUP 10 = IF  1 TSRC-LINE +!  THEN
  ;

: TSRC-SKIP-WS  ( -- )
  BEGIN
    TSRC-PEEK DUP 0< IF  DROP EXIT  THEN
    DUP BL > IF  DROP EXIT  THEN
    DROP TSRC-GETC DROP
  AGAIN
  ;

: TSRC-SKIP-LINE  ( -- )
  BEGIN
    TSRC-GETC DUP 0< IF  DROP EXIT  THEN
    10 = IF EXIT THEN
  AGAIN
  ;

: TSRC-SKIP-PAREN  ( -- )
  BEGIN
    TSRC-GETC DUP 0< IF  DROP S" unclosed (" TSRC-ERR  THEN
    [CHAR] ) = IF EXIT THEN
  AGAIN
  ;

\ Multi-line block comment body: skip until closing {
: TSRC-SKIP-BLOCK  ( -- )
  BEGIN
    TSRC-GETC DUP 0< IF  DROP S" unclosed block comment (need {)" TSRC-ERR  THEN
    [CHAR] { = IF EXIT THEN
  AGAIN
  ;

\ Match upcoming token (already saw leading \) against ca u (e.g. S" ANS").
\ On match: consume name chars, return true. Else restore I and return false.
: TSRC-MATCH-DIR?  ( ca u -- f )
  TSRC-I @ >R
  TSRC-GETC DROP                         \ consume '\'
  0 DO
    TSRC-PEEK DUP 0< IF
      DROP UNLOOP R> TSRC-I ! FALSE EXIT
    THEN
    DUP BL <= IF
      DROP UNLOOP R> TSRC-I ! FALSE EXIT
    THEN
    OVER C@ 32 OR <> IF
      DROP UNLOOP R> TSRC-I ! FALSE EXIT
    THEN
    TSRC-GETC DROP 1+
  LOOP DROP
  \ Must be end of token (whitespace or EOF)
  TSRC-PEEK DUP 0< IF DROP R> DROP TRUE EXIT THEN
  BL <= IF R> DROP TRUE EXIT THEN
  R> TSRC-I ! FALSE
  ;

\ \ANS / \TCOM — if directive is false, skip rest of line (like \)
: TSRC-TRY-DIRECTIVE  ( -- handled? )
  S" ANS" TSRC-MATCH-DIR? IF
    ['] \ANS >BODY @ 0= IF TSRC-SKIP-LINE THEN
    TRUE EXIT
  THEN
  S" TCOM" TSRC-MATCH-DIR? IF
    ['] \TCOM >BODY @ 0= IF TSRC-SKIP-LINE THEN
    TRUE EXIT
  THEN
  FALSE
  ;

: TSRC-TOKEN  ( -- ca u )
  TSRC-SKIP-WS
  TSRC-I @ TSRC-TOK-AT !
  TSRC-EOF? IF  TSRC-WORD 0 EXIT  THEN
  \ \\ … {  multi-line (two backslashes); checked before single-\ line comment
  TSRC-PEEK [CHAR] \ = IF
    TSRC-I @ 1+ TSRC-LEN @ < IF
      TSRC-BUF TSRC-I @ 1+ + C@ [CHAR] \ = IF
        TSRC-GETC DROP TSRC-GETC DROP
        TSRC-SKIP-BLOCK RECURSE EXIT
      THEN
    THEN
    \ \ANS / \TCOM dual-load directives (before treating \ as line comment)
    TSRC-TRY-DIRECTIVE IF  RECURSE EXIT  THEN
    TSRC-GETC DROP TSRC-SKIP-LINE RECURSE EXIT
  THEN
  \ } … {  alias for the same multi-line block
  TSRC-PEEK [CHAR] } = IF
    TSRC-GETC DROP TSRC-SKIP-BLOCK RECURSE EXIT
  THEN
  TSRC-PEEK [CHAR] ( = IF
    TSRC-GETC DROP TSRC-SKIP-PAREN RECURSE EXIT
  THEN
  0 TSRC-WORD C!
  BEGIN
    TSRC-PEEK DUP 0< IF  DROP TSRC-WORD COUNT EXIT  THEN
    DUP BL <= IF  DROP TSRC-WORD COUNT EXIT  THEN
    DROP                           \ discard peek; TSRC-GETC re-reads
    TSRC-GETC
    TSRC-WORD C@ 126 U< IF
      TSRC-WORD COUNT + C!
      TSRC-WORD C@ 1+ TSRC-WORD C!
    ELSE DROP THEN
  AGAIN
  ;

: TSRC-EQ  ( ca1 u1 ca2 u2 -- f )
  ROT 2DUP <> IF  2DROP 2DROP FALSE EXIT  THEN
  DROP
  0 DO
    OVER C@ OVER C@ <> IF  2DROP UNLOOP FALSE EXIT  THEN
    SWAP 1+ SWAP 1+
  LOOP
  2DROP TRUE
  ;

: TSRC-DIGIT  ( c base -- n | -1 )
  >R
  DUP [CHAR] 0 [CHAR] 9 1+ WITHIN IF
    [CHAR] 0 - DUP R@ < IF  R> DROP EXIT  THEN
    DROP R> DROP -1 EXIT
  THEN
  DUP [CHAR] A [CHAR] F 1+ WITHIN IF
    [CHAR] A - 10 + DUP R@ < IF  R> DROP EXIT  THEN
    DROP R> DROP -1 EXIT
  THEN
  DUP [CHAR] a [CHAR] f 1+ WITHIN IF
    [CHAR] a - 10 + DUP R@ < IF  R> DROP EXIT  THEN
    DROP R> DROP -1 EXIT
  THEN
  DROP R> DROP -1
  ;

\ ( ca u -- n true | false )  always consumes ca u
: TSRC->NUMBER  ( ca u -- n true | false )
  DUP 0= IF  2DROP FALSE EXIT  THEN
  0 TSRC-ACC !  FALSE TSRC-OK !
  FALSE >R                           \ sign flag on R
  OVER C@ [CHAR] - = IF
    1 /STRING DUP 0= IF  R> DROP 2DROP FALSE EXIT  THEN
    R> DROP TRUE >R
  THEN
  OVER C@ [CHAR] $ = IF
    1 /STRING DUP 0= IF  R> DROP 2DROP FALSE EXIT  THEN
    16
  ELSE  10  THEN  TSRC-BASE !
  BEGIN DUP WHILE
    OVER C@ TSRC-BASE @ TSRC-DIGIT
    DUP 0< IF  DROP 2DROP R> DROP FALSE EXIT  THEN
    TSRC-ACC @ TSRC-BASE @ * + TSRC-ACC !
    TRUE TSRC-OK !
    1 /STRING
  REPEAT
  2DROP
  TSRC-OK @ 0= IF  R> DROP FALSE EXIT  THEN
  TSRC-ACC @
  R> IF NEGATE THEN
  TRUE
  ;

: TSRC-WIPE  ( -- )  BEGIN DEPTH WHILE DROP REPEAT ;

: TSRC-SLICE-SAVE  ( off0 off1 -- addr u )
  OVER - DUP 0> 0= IF
    NIP DROP  TSRC-CTPOOL TSRC-CTP @ +  0  EXIT
  THEN
  \ off0 u
  DUP TSRC-CTP @ + /TSRC-CTPOOL U> IF
    2DROP S" TSRC: defining-word source too large" TSRC-ERR
  THEN
  TSRC-CTP @ TSRC-CTPOOL + >R     \ off0 u  R: dest
  DUP TSRC-CTP +!                 \ off0 u
  SWAP TSRC-BUF +                 \ u src
  R@ ROT                          \ src dest u
  MOVE
  R> TSRC-CTP @ TSRC-CTPOOL + OVER -   \ dest u   (ctp already advanced)
  ;

: TSRC-REPLAY  ( addr u in-colon -- )
  TSRC-BUF-ADDR @ >R  TSRC-BUF-CAP @ >R
  TSRC-LEN @ >R  TSRC-I @ >R  TSRC-LINE @ >R
  TSRC-IN-COLON @ >R
  TSRC-IN-COLON !
  DUP TSRC-LEN !  DUP TSRC-BUF-CAP !
  SWAP TSRC-BUF-ADDR !  DROP
  0 TSRC-I !  1 TSRC-LINE !
  BEGIN
    TSRC-TOKEN DUP 0= IF  2DROP TRUE  ELSE TSRC-DISPATCH FALSE THEN
  UNTIL
  R> TSRC-IN-COLON !
  R> TSRC-LINE !  R> TSRC-I !  R> TSRC-LEN !
  R> TSRC-BUF-CAP !  R> TSRC-BUF-ADDR !
  ;

: TSRC-START-COLON-CODE  ( -- )
  START-T:
  HERE-T M-TMP !
  ENTRY-LANDING
  ;

: TSRC-COLON  ( ca u -- )
  \ Name already on stack — do NOT use (T-COOKIE)/CREATE (would BL WORD from TIB).
  TSRC-IN-COLON @ IF  2DROP S" nested :" TSRC-ERR  THEN
  TSRC-START-COLON-CODE
  2DUP PAD 2 CELLS + PLACE
  PAD 2 CELLS + COMP-HEADER
  SYM-TARGET M-TMP @ SYM-DEFINE TSRC-LAST !
  TSRC-I @ TSRC-BODY0 !
  FALSE TSRC-NONAME !
  FALSE TSRC-DEFINER !
  FALSE TSRC-SKIP-CT !
  FALSE TSRC-IN-DOES !
  TRUE TO ?INTERPRETIVE
  TRUE TSRC-IN-COLON !
  ;

: TSRC-NONAME-START  ( -- )
  TSRC-IN-COLON @ IF  S" nested :NONAME" TSRC-ERR  THEN
  TSRC-START-COLON-CODE
  TSRC-I @ TSRC-BODY0 !
  TRUE TSRC-NONAME !
  FALSE TSRC-DEFINER !
  FALSE TSRC-SKIP-CT !
  FALSE TSRC-IN-DOES !
  -1 TSRC-LAST !
  TRUE TO ?INTERPRETIVE
  TRUE TSRC-IN-COLON !
  ;

: TSRC-FINISH-DEFINER  ( -- )
  TSRC-LAST @ DUP 0< IF  DROP S" ; definer has no name" TSRC-ERR  THEN
  TSRC-DOES-XT @ 0= IF  TSRC-TOK-AT @ TSRC-CT1 !  THEN
  TSRC-CT0 @ TSRC-CT1 @ TSRC-SLICE-SAVE  ( addr u )
  TSRC-LAST @ SYM-L!
  TSRC-LAST @ SYM-ADDR!
  TSRC-DOES-XT @ TSRC-LAST @ SYM-X!
  SYM-DEFINER TSRC-LAST @ SYM-TYPE!
  ;

: TSRC-ATTACH-DOES  ( xt -- )
  TSRC-LAST @ DUP 0< IF  DROP DROP S" DOES> with no CREATE" TSRC-ERR  THEN
  DUP SYM-TYPE@ DUP SYM-DATA = SWAP SYM-DOES = OR 0= IF
    DROP DROP S" DOES> needs CREATE" TSRC-ERR
  THEN
  DUP SYM-DOES SWAP SYM-TYPE!
  SYM-X!
  ;

: TSRC-SEMI  ( -- )
  TSRC-IN-COLON @ 0= IF  S" ; outside :" TSRC-ERR  THEN
  TSRC-TOK-AT @ TSRC-BODY1 !
  END-T:
  FALSE TO ?INTERPRETIVE
  FALSE TSRC-IN-COLON !
  FALSE TSRC-SKIP-CT !
  TSRC-DEFINER @ IF
    TSRC-FINISH-DEFINER
    FALSE TSRC-DEFINER !
    TSRC-WIPE
    EXIT
  THEN
  TSRC-IN-DOES @ IF
    M-TMP @ TSRC-ATTACH-DOES
    FALSE TSRC-IN-DOES !
    TSRC-WIPE
    EXIT
  THEN
  TSRC-NONAME @ IF
    M-TMP @ >R
    FALSE TSRC-NONAME !
    TSRC-WIPE
    R> EXIT
  THEN
  TSRC-WIPE
  ;

: TSRC-CONSTANT  ( ca u -- )
  TSRC-IN-COLON @ IF  2DROP S" CONSTANT inside :" TSRC-ERR  THEN
  DEPTH 0= IF  2DROP S" CONSTANT needs n" TSRC-ERR  THEN
  ROT SYM-CONST SWAP SYM-ADD TSRC-LAST !
  ;

: TSRC-VOCABULARY  ( ca u -- )
  TSRC-IN-COLON @ IF  2DROP S" VOCABULARY inside :" TSRC-ERR  THEN
  SYM-VOCAB TWL-NEXT @ SYM-ADD TSRC-LAST !
  1 TWL-NEXT +!
  ;

: TSRC-SET-WID  ( ix -- )
  SYM-ADDR@ TWL-ORDER !
  TWL-# @ 0= IF  1 TWL-# !  THEN
  ;

: TSRC-FORTH  ( -- )
  TSRC-IN-COLON @ IF  S" FORTH inside :" TSRC-ERR  THEN
  TWL-FORTH TWL-ORDER !
  TWL-# @ 0= IF  1 TWL-# !  THEN
  ;

: TSRC-ALSO  ( -- )
  TSRC-IN-COLON @ IF  S" ALSO inside :" TSRC-ERR  THEN
  TWL-# @ #TWL-ORDER U>= IF  S" search order full" TSRC-ERR  THEN
  TWL-ORDER TWL-ORDER CELL+  TWL-# @ CELLS CMOVE>
  1 TWL-# +!
  ;

: TSRC-ONLY  ( -- )
  TSRC-IN-COLON @ IF  S" ONLY inside :" TSRC-ERR  THEN
  1 TWL-# !
  TWL-ORDER #TWL-ORDER CELLS ERASE
  TWL-FORTH TWL-ORDER !
  ;

: TSRC-DEFINITIONS  ( -- )
  TSRC-IN-COLON @ IF  S" DEFINITIONS inside :" TSRC-ERR  THEN
  TWL-ORDER @ TWL-CURRENT !
  ;

: TSRC-XT-OF  ( ix -- xt )
  DUP SYM-TYPE@ DUP SYM-TARGET = OVER SYM-LIBRARY = OR SWAP SYM-CODE = OR IF
    SYM-ADDR@ EXIT
  THEN
  DROP S" ' needs a colon or library word" TSRC-ERR
  ;

: TSRC-TICK  ( -- )
  TSRC-TOKEN DUP 0= IF  2DROP S" ' needs a name" TSRC-ERR  THEN
  2DUP SYM-FIND IF
    NIP NIP TSRC-XT-OF
    TSRC-IN-COLON @ IF  G,  THEN
  ELSE
    TYPE S"  ?" TSRC-ERR
  THEN
  ;

: TSRC-XT-SYM?  ( ix -- f )
  SYM-TYPE@ DUP SYM-TARGET = OVER SYM-LIBRARY = OR SWAP SYM-CODE = OR
  ;

: TSRC-BUILD-FIND-TABLE  ( -- )
  [DEFINED] TCOM-FIND-DADDR [IF]
    CELL-ALIGN-D
    HERE-D >R
    0 ,-D
    0 TSRC-ACC !
    SYM-N @ DUP 0= IF  DROP R> DROP EXIT  THEN
    1- TSRC-BASE !
    BEGIN TSRC-BASE @ 0< 0= WHILE
      TSRC-BASE @ TSRC-XT-SYM? IF
        TSRC-BASE @ SYM-ADDR@ ,-D
        TSRC-BASE @ SYM-IMM? IF  1  ELSE  -1  THEN  ,-D
        TSRC-BASE @ SYM-NBUF  /SNAME S,-D
        1 TSRC-ACC +!
      THEN
      -1 TSRC-BASE +!
    REPEAT
    TSRC-ACC @ R@ !-D
    R> TCOM-FIND-DADDR !-D
  [THEN]
  ;

: TSRC-IMMEDIATE  ( -- )
  TSRC-IN-COLON @ IF  S" IMMEDIATE inside :" TSRC-ERR  THEN
  TSRC-LAST @ DUP 0< IF  DROP S" IMMEDIATE with no definition" TSRC-ERR  THEN
  DUP SYM-TYPE@ SYM-TARGET <> IF
    DROP S" IMMEDIATE needs a colon definition" TSRC-ERR
  THEN
  TSRC-BODY0 @ TSRC-BODY1 @ TSRC-SLICE-SAVE  ( addr u )
  TSRC-LAST @ SYM-L!
  TSRC-LAST @ SYM-X!
  1 TSRC-LAST @ SYM-F!
  ;

: TSRC-MARK-DEFINER  ( -- )
  HERE-T M-TMP @ <> IF  S" CREATE must be first in a defining word" TSRC-ERR  THEN
  TRUE TSRC-DEFINER !
  TRUE TSRC-SKIP-CT !
  TSRC-I @ TSRC-CT0 !
  0 TSRC-DOES-XT !
  ;

: TSRC-DOES>  ( -- )
  TSRC-IN-COLON @ IF
    TSRC-DEFINER @ 0= IF  S" DOES> without CREATE" TSRC-ERR  THEN
    TSRC-SKIP-CT @ 0= IF  S" extra DOES>" TSRC-ERR  THEN
    TSRC-TOK-AT @ TSRC-CT1 !
    FALSE TSRC-SKIP-CT !
    TSRC-START-COLON-CODE
    M-TMP @ TSRC-DOES-XT !
    EXIT
  THEN
  \ Top-level: attach a does-body to the last CREATE
  TSRC-LAST @ 0< IF  S" DOES> with no CREATE" TSRC-ERR  THEN
  TSRC-START-COLON-CODE
  TRUE TSRC-IN-DOES !
  TRUE TSRC-IN-COLON !
  TRUE TO ?INTERPRETIVE
  ;

: TSRC-LBRACK  ( -- )
  TSRC-IN-COLON @ 0= IF  S" [ outside :" TSRC-ERR  THEN
  FALSE TSRC-IN-COLON !
  TRUE TSRC-BRACKET !
  ;

: TSRC-RBRACK  ( -- )
  TSRC-BRACKET @ 0= IF  S" ] without [" TSRC-ERR  THEN
  FALSE TSRC-BRACKET !
  TRUE TSRC-IN-COLON !
  ;

: TSRC-LITERAL  ( -- )
  TSRC-IN-COLON @ 0= IF  S" LITERAL outside :" TSRC-ERR  THEN
  DEPTH 0= IF  S" LITERAL underflow" TSRC-ERR  THEN
  G,
  ;

: TSRC-RECURSE  ( -- )
  TSRC-IN-COLON @ 0= IF  S" RECURSE outside :" TSRC-ERR  THEN
  M-TMP @ COMP-CALL
  ;

: TSRC-RUN-IMM  ( ix -- )
  DUP SYM-L@ 0= IF  DROP S" IMMEDIATE word has no body" TSRC-ERR  THEN
  DUP SYM-X@ SWAP SYM-L@ TRUE TSRC-REPLAY
  ;

: TSRC-VARIABLE  ( ca u -- )
  \ ( ca u ) name — one cell in target DATA; SYM-DATA holds daddr (not host)
  TSRC-IN-COLON @ IF  2DROP S" VARIABLE inside :" TSRC-ERR  THEN
  CELL-ALIGN-D
  HERE-D                       ( ca u daddr )
  0 OVER !-D
  T-CELL ALLOT-D
  SYM-DATA SWAP SYM-ADD TSRC-LAST !
  ;

\ CREATE name — data symbol at HERE-D; no automatic allot (use ALLOT / ,)
: TSRC-CREATE  ( ca u -- ix )
  TSRC-IN-COLON @ IF  2DROP S" CREATE inside :" TSRC-ERR  THEN
  CELL-ALIGN-D
  HERE-D                       ( ca u daddr )
  SYM-DATA SWAP SYM-ADD
  DUP TSRC-LAST !
  ;

: TSRC-RUN-DEFINER  ( ix -- )
  TSRC-IN-COLON @ IF  DROP S" defining word inside :" TSRC-ERR  THEN
  >R
  TSRC-TOKEN DUP 0= IF  2DROP R> DROP S" defining word needs a name" TSRC-ERR  THEN
  TSRC-CREATE DROP
  R@ SYM-L@ IF
    R@ SYM-ADDR@  R@ SYM-L@  FALSE TSRC-REPLAY
  THEN
  R> SYM-X@ DUP IF  TSRC-ATTACH-DOES  ELSE DROP THEN
  ;

\ VALUE — n already under (ca u) on host stack; SYM-VALUE auto-fetches
: TSRC-VALUE  ( ca u -- )
  TSRC-IN-COLON @ IF  2DROP S" VALUE inside :" TSRC-ERR  THEN
  DEPTH 2 <= IF  2DROP S" VALUE needs initial n" TSRC-ERR  THEN
  CELL-ALIGN-D
  HERE-D >R                      \ n ca u  R: daddr
  ROT                            \ ca u n
  R@ !-D                         \ ca u
  T-CELL ALLOT-D
  SYM-VALUE R> SYM-ADD TSRC-LAST !
  ;

\ TO / =: name — compile store into a VALUE (or VARIABLE cell)
: TSRC-TO  ( -- )
  TSRC-IN-COLON @ 0= IF  S" TO outside :" TSRC-ERR  THEN
  TSRC-TOKEN
  DUP 0= IF  2DROP S" TO needs a name" TSRC-ERR  THEN
  2DUP SYM-FIND IF
    >R 2DROP R>                          \ ix (IF ate true)
  ELSE
    TYPE S"  ?" TSRC-ERR
  THEN
  DUP SYM-TYPE@ DUP SYM-VALUE = SWAP SYM-DATA = OR 0= IF
    DROP S" TO needs VALUE or VARIABLE" TSRC-ERR
  THEN
  SYM-ADDR@ COMP-DATA-ADDR
  COMP-STORE
  ;

\ Top-level ,  ( n -- ) store cell at HERE-D and allot
: TSRC-COMMA  ( -- )
  TSRC-IN-COLON @ IF  S" , inside : — use literals" TSRC-ERR  THEN
  DEPTH 0= IF  S" , underflow" TSRC-ERR  THEN
  HERE-D !-D
  T-CELL ALLOT-D
  ;

\ Top-level ALLOT ( n -- )
: TSRC-ALLOT  ( -- )
  TSRC-IN-COLON @ IF  S" ALLOT inside :" TSRC-ERR  THEN
  DEPTH 0= IF  S" ALLOT underflow" TSRC-ERR  THEN
  ALLOT-D
  ;

: TSRC-HOST-EXEC  ( ca u -- )
  DUP PAD C!
  PAD 1+ SWAP MOVE
  PAD FIND IF
    EXECUTE
  ELSE
    COUNT TYPE S"  (host) not found — load target pack first" TSRC-ERR
  THEN
  ;

: TSRC-LIB-CALL  ( ca u -- )
  2DUP SYM-FIND IF
    NIP NIP SYM-ADDR@ COMP-CALL
  ELSE
    TYPE S"  prim missing" TSRC-ERR
  THEN
  ;

\ +!> name  ( n -- )  NAME @ n + TO NAME
: TSRC-+TO  ( -- )
  TSRC-IN-COLON @ 0= IF  S" +!> outside :" TSRC-ERR  THEN
  TSRC-TOKEN
  DUP 0= IF  2DROP S" +!> needs a name" TSRC-ERR  THEN
  2DUP SYM-FIND IF
    >R 2DROP R>
  ELSE
    TYPE S"  ?" TSRC-ERR
  THEN
  DUP SYM-TYPE@ DUP SYM-VALUE = SWAP SYM-DATA = OR 0= IF
    DROP S" +!> needs VALUE or VARIABLE" TSRC-ERR
  THEN
  DUP >R
  SYM-ADDR@ COMP-DATA-ADDR  COMP-FETCH
  S" PLUS#" TSRC-LIB-CALL
  R> SYM-ADDR@ COMP-DATA-ADDR  COMP-STORE
  ;

\ ASCII double-quote — avoid [CHAR] " inside definitions (breaks some 64Forth parses)
34 CONSTANT TSRC-QUOT

\ After S" or ." — copy chars until " into T-DATA; compile addr + len
: TSRC-COMPILE-STRING  ( -- )
  TSRC-IN-COLON @ 0= IF  S" string outside :" TSRC-ERR  THEN
  \ skip one blank after S" / ." if present (classic Forth style)
  TSRC-PEEK BL = IF  TSRC-GETC DROP  THEN
  HERE-D >R
  BEGIN
    TSRC-GETC DUP 0< IF
      DROP R> DROP S" unclosed string" TSRC-ERR
    THEN
    DUP TSRC-QUOT = IF
      DROP
      R@ COMP-DATA-ADDR          \ runtime address of string bytes
      HERE-D R> - G,             \ length
      EXIT
    THEN
    C,-D
  AGAIN
  ;

\ CHAR / [CHAR] — parse next word; compile first character as a literal
: TSRC-COMPILE-CHAR  ( -- )
  TSRC-IN-COLON @ 0= IF  S" CHAR outside :" TSRC-ERR  THEN
  TSRC-TOKEN
  DUP 0= IF  2DROP S" CHAR needs a character" TSRC-ERR  THEN
  DROP C@ G,                         \ ( ca u -- ) first char as lit
  ;

: TSRC-COMPILE-TICK  ( -- )
  TSRC-IN-COLON @ 0= IF  S" ['] outside :" TSRC-ERR  THEN
  TSRC-TOKEN
  DUP 0= IF  2DROP S" ['] needs a name" TSRC-ERR  THEN
  2DUP SYM-FIND IF
    NIP NIP SYM-ADDR@ G,
  ELSE
    TYPE S"  ?" TSRC-ERR
  THEN
  ;

: TSRC-STORE-BASE  ( n -- )
  COMP-SINGLE
  TCOM-BASE-DADDR COMP-DATA-ADDR
  COMP-STORE
  ;

: TSRC-SHARPS-EMIT  ( -- )
  S" TBEGIN" TSRC-HOST-EXEC
  S" SHARP#" TSRC-LIB-CALL
  S" 2DUP#" TSRC-LIB-CALL
  S" OR#" TSRC-LIB-CALL
  S" ZEQ#" TSRC-LIB-CALL
  S" TUNTIL" TSRC-HOST-EXEC
  ;

: TSRC-UDOT  ( -- )
  0 G,
  S" LTSHARP#" TSRC-LIB-CALL
  TSRC-SHARPS-EMIT
  S" SHARPGT#" TSRC-LIB-CALL
  S" TYPE#" TSRC-LIB-CALL
  S" SPACE#" TSRC-LIB-CALL
  ;

: TSRC-DOT  ( -- )
  S" DUP#" TSRC-LIB-CALL
  S" ABS#" TSRC-LIB-CALL
  0 G,
  S" LTSHARP#" TSRC-LIB-CALL
  TSRC-SHARPS-EMIT
  S" ROT#" TSRC-LIB-CALL
  S" SIGN#" TSRC-LIB-CALL
  S" SHARPGT#" TSRC-LIB-CALL
  S" TYPE#" TSRC-LIB-CALL
  S" SPACE#" TSRC-LIB-CALL
  ;

: TSRC-DOTR  ( -- )
  S" TOR#" TSRC-LIB-CALL
  S" DUP#" TSRC-LIB-CALL
  S" ABS#" TSRC-LIB-CALL
  0 G,
  S" LTSHARP#" TSRC-LIB-CALL
  TSRC-SHARPS-EMIT
  S" ROT#" TSRC-LIB-CALL
  S" SIGN#" TSRC-LIB-CALL
  S" SHARPGT#" TSRC-LIB-CALL
  S" FROMR#" TSRC-LIB-CALL
  S" OVER#" TSRC-LIB-CALL
  S" MINUS#" TSRC-LIB-CALL
  0 G,
  S" MAX#" TSRC-LIB-CALL
  S" SPACES#" TSRC-LIB-CALL
  S" TYPE#" TSRC-LIB-CALL
  ;

: TSRC-UDOTR  ( -- )
  S" TOR#" TSRC-LIB-CALL
  0 G,
  S" LTSHARP#" TSRC-LIB-CALL
  TSRC-SHARPS-EMIT
  S" SHARPGT#" TSRC-LIB-CALL
  S" FROMR#" TSRC-LIB-CALL
  S" OVER#" TSRC-LIB-CALL
  S" MINUS#" TSRC-LIB-CALL
  0 G,
  S" MAX#" TSRC-LIB-CALL
  S" SPACES#" TSRC-LIB-CALL
  S" TYPE#" TSRC-LIB-CALL
  ;

\ True if (ca u) is the two-char token S"
: TSRC-SQUOT?  ( ca u -- f )
  2 <> IF  DROP FALSE EXIT  THEN
  DUP C@ [CHAR] S = IF
    1+ C@ TSRC-QUOT =
  ELSE  DROP FALSE  THEN
  ;

\ True if (ca u) is the two-char token ."
: TSRC-DOTQUOT?  ( ca u -- f )
  2 <> IF  DROP FALSE EXIT  THEN
  DUP C@ [CHAR] . = IF
    1+ C@ TSRC-QUOT =
  ELSE  DROP FALSE  THEN
  ;

: TSRC-PRIM?  ( ca u -- f )
  2DUP S" +" TSRC-EQ IF  2DROP S" PLUS#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" -" TSRC-EQ IF  2DROP S" MINUS#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" *" TSRC-EQ IF  2DROP S" MUL#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" AND" TSRC-EQ IF  2DROP S" AND#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" OR" TSRC-EQ IF  2DROP S" OR#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" INVERT" TSRC-EQ IF  2DROP S" INVERT#" TSRC-LIB-CALL TRUE EXIT  THEN
  \ ANS/Win32Forth NOT is logical 0= (not bitwise INVERT). CSET flags
  \ were 0/1; INVERT 0 = -1 and INVERT 1 = -2, so NOT always looked true.
  2DUP S" NOT" TSRC-EQ IF  2DROP S" ZEQ#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" 2*" TSRC-EQ IF  2DROP S" 2STAR#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" LSHIFT" TSRC-EQ IF  2DROP S" LSHIFT#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" RSHIFT" TSRC-EQ IF  2DROP S" RSHIFT#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" UNLOOP" TSRC-EQ IF  2DROP S" UNLOOP#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" 2/" TSRC-EQ IF  2DROP S" 2SLASH#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" NEGATE" TSRC-EQ IF  2DROP S" NEGATE#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" CELLS" TSRC-EQ IF  2DROP S" CELLS#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" CELL+" TSRC-EQ IF  2DROP 8 G, S" PLUS#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" 2@" TSRC-EQ IF  2DROP S" 2FETCH#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" 2!" TSRC-EQ IF  2DROP S" 2STORE#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" CELL-" TSRC-EQ IF  2DROP S" CELLMINUS#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" COUNT" TSRC-EQ IF  2DROP S" COUNT#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" FILL" TSRC-EQ IF  2DROP S" FILL#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" ERASE" TSRC-EQ IF  2DROP S" ERASE#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" CMOVE>" TSRC-EQ IF  2DROP S" CMOVEUP#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" MOVE" TSRC-EQ IF  2DROP S" MOVE#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" D+" TSRC-EQ IF  2DROP S" DPLUS#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" D-" TSRC-EQ IF  2DROP S" DMINUS#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" S>D" TSRC-EQ IF  2DROP S" STOD#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" D>S" TSRC-EQ IF  2DROP S" DTOS#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" C@" TSRC-EQ IF  2DROP S" CFETCH#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" C!" TSRC-EQ IF  2DROP S" CSTORE#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" +!" TSRC-EQ IF  2DROP S" PLUSSTORE#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" 2DROP" TSRC-EQ IF  2DROP S" 2DROP#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" XOR" TSRC-EQ IF  2DROP S" XOR#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" 0<" TSRC-EQ IF  2DROP S" ZLT#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" ABS" TSRC-EQ IF  2DROP S" ABS#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" MIN" TSRC-EQ IF  2DROP S" MIN#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" MAX" TSRC-EQ IF  2DROP S" MAX#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" PICK" TSRC-EQ IF  2DROP S" PICK#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" 2SWAP" TSRC-EQ IF  2DROP S" 2SWAP#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" 2OVER" TSRC-EQ IF  2DROP S" 2OVER#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" TUCK" TSRC-EQ IF  2DROP S" TUCK#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" ?DUP" TSRC-EQ IF  2DROP S" QDUP#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" ROLL" TSRC-EQ IF  2DROP S" ROLL#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" DEPTH" TSRC-EQ IF  2DROP S" DEPTH#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" 0>" TSRC-EQ IF  2DROP S" ZGT#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" 0<>" TSRC-EQ IF  2DROP S" ZNE#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" <=" TSRC-EQ IF  2DROP S" LE#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" >=" TSRC-EQ IF  2DROP S" GE#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" U<" TSRC-EQ IF  2DROP S" ULT#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" U>" TSRC-EQ IF  2DROP S" UGT#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" WITHIN" TSRC-EQ IF  2DROP S" WITHIN#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" EXECUTE" TSRC-EQ IF  2DROP S" EXEC#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" FIND" TSRC-EQ IF  2DROP S" FIND#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" CATCH" TSRC-EQ IF  2DROP S" CATCH#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" THROW" TSRC-EQ IF  2DROP S" THROW#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" ALLOCATE" TSRC-EQ IF  2DROP S" ALLOC#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" FREE" TSRC-EQ IF  2DROP S" FREE#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" RESIZE" TSRC-EQ IF  2DROP S" RESIZE#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" >R" TSRC-EQ IF  2DROP S" TOR#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" R>" TSRC-EQ IF  2DROP S" FROMR#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" R@" TSRC-EQ IF  2DROP S" RFETCH#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" CMOVE" TSRC-EQ IF  2DROP S" CMOVE#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" SPACES" TSRC-EQ IF  2DROP S" SPACES#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" MOD" TSRC-EQ IF
    2DROP
    S" TOR#" TSRC-LIB-CALL  S" STOD#" TSRC-LIB-CALL
    S" FROMR#" TSRC-LIB-CALL  S" SMREM#" TSRC-LIB-CALL
    S" DROP#" TSRC-LIB-CALL  TRUE EXIT
  THEN
  2DUP S" /" TSRC-EQ IF
    2DROP
    S" TOR#" TSRC-LIB-CALL  S" STOD#" TSRC-LIB-CALL
    S" FROMR#" TSRC-LIB-CALL  S" SMREM#" TSRC-LIB-CALL
    S" NIP#" TSRC-LIB-CALL  TRUE EXIT
  THEN
  2DUP S" /MOD" TSRC-EQ IF
    2DROP
    S" TOR#" TSRC-LIB-CALL  S" STOD#" TSRC-LIB-CALL
    S" FROMR#" TSRC-LIB-CALL  S" SMREM#" TSRC-LIB-CALL  TRUE EXIT
  THEN
  2DUP S" */" TSRC-EQ IF
    2DROP
    S" TOR#" TSRC-LIB-CALL  S" MSTAR#" TSRC-LIB-CALL
    S" FROMR#" TSRC-LIB-CALL  S" SMREM#" TSRC-LIB-CALL
    S" NIP#" TSRC-LIB-CALL  TRUE EXIT
  THEN
  2DUP S" */MOD" TSRC-EQ IF
    2DROP
    S" TOR#" TSRC-LIB-CALL  S" MSTAR#" TSRC-LIB-CALL
    S" FROMR#" TSRC-LIB-CALL  S" SMREM#" TSRC-LIB-CALL  TRUE EXIT
  THEN
  2DUP S" M*" TSRC-EQ IF  2DROP S" MSTAR#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" UM*" TSRC-EQ IF  2DROP S" UMSTAR#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" UM/MOD" TSRC-EQ IF  2DROP S" UMMOD#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" SM/REM" TSRC-EQ IF  2DROP S" SMREM#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" FM/MOD" TSRC-EQ IF  2DROP S" FMMOD#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" 1-" TSRC-EQ IF  2DROP S" 1MINUS#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" 1+" TSRC-EQ IF  2DROP S" 1PLUS#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" KEY?" TSRC-EQ IF  2DROP S" KEYQ#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" BYE" TSRC-EQ IF  2DROP S" BYE#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" AT" TSRC-EQ IF  2DROP S" AT#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" CLS" TSRC-EQ IF  2DROP S" CLS#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" GET-CHAR" TSRC-EQ IF  2DROP S" GETCHAR#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" TONE" TSRC-EQ IF  2DROP S" TONE#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" TIME-RESET" TSRC-EQ IF  2DROP S" TIMERST#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" 10TH-ELAPSED" TSRC-EQ IF  2DROP S" TENTHEL#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" TENTHS" TSRC-EQ IF  2DROP S" TENTHS#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" EXIT" TSRC-EQ IF  2DROP S" RET," TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" UPC" TSRC-EQ IF  2DROP S" UPC#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" TRUE" TSRC-EQ IF  2DROP -1 G, TRUE EXIT  THEN
  2DUP S" FALSE" TSRC-EQ IF  2DROP 0 G, TRUE EXIT  THEN
  2DUP S" DUP" TSRC-EQ IF  2DROP S" DUP#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" DROP" TSRC-EQ IF  2DROP S" DROP#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" SWAP" TSRC-EQ IF  2DROP S" SWAP#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" OVER" TSRC-EQ IF  2DROP S" OVER#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" @" TSRC-EQ IF  2DROP S" G@" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" !" TSRC-EQ IF  2DROP S" G!" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" TYPE" TSRC-EQ IF  2DROP S" TYPE#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" ETYPE" TSRC-EQ IF  2DROP S" ETYPE#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" EEMIT" TSRC-EQ IF  2DROP S" EEMIT#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" ECR" TSRC-EQ IF  2DROP S" ECR#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" WINDOW" TSRC-EQ IF  2DROP S" WINDOW#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" APP-NAME" TSRC-EQ IF  2DROP S" APP-NAME#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" WRITE" TSRC-EQ IF  2DROP S" WRITE#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" READ" TSRC-EQ IF  2DROP S" READ#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" KEY" TSRC-EQ IF  2DROP S" KEY#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" ACCEPT" TSRC-EQ IF  2DROP S" ACCEPT#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" CLOSE" TSRC-EQ IF  2DROP S" CLOSE#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" OPEN-R" TSRC-EQ IF  2DROP S" OPEN-R" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" OPEN-W" TSRC-EQ IF  2DROP S" OPEN-W" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" LINE-BUF" TSRC-EQ IF  2DROP S" LINE-BUF" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" EMIT" TSRC-EQ IF  2DROP S" EMIT#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" CHAR" TSRC-EQ IF  2DROP TSRC-COMPILE-CHAR TRUE EXIT  THEN
  2DUP S" [CHAR]" TSRC-EQ IF  2DROP TSRC-COMPILE-CHAR TRUE EXIT  THEN
  2DUP S" [']" TSRC-EQ IF  2DROP TSRC-COMPILE-TICK TRUE EXIT  THEN
  2DUP S" I" TSRC-EQ IF  2DROP S" TI," TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" J" TSRC-EQ IF  2DROP S" TJ," TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" CR" TSRC-EQ IF  2DROP S" CR#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" SPACE" TSRC-EQ IF  2DROP S" SPACE#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" ." TSRC-EQ IF  2DROP TSRC-DOT TRUE EXIT  THEN
  2DUP S" <#" TSRC-EQ IF  2DROP S" LTSHARP#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" HOLD" TSRC-EQ IF  2DROP S" HOLD#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" SIGN" TSRC-EQ IF  2DROP S" SIGN#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" #" TSRC-EQ IF  2DROP S" SHARP#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" #S" TSRC-EQ IF  2DROP TSRC-SHARPS-EMIT TRUE EXIT  THEN
  2DUP S" #>" TSRC-EQ IF  2DROP S" SHARPGT#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" U." TSRC-EQ IF  2DROP TSRC-UDOT TRUE EXIT  THEN
  2DUP S" .R" TSRC-EQ IF  2DROP TSRC-DOTR TRUE EXIT  THEN
  2DUP S" U.R" TSRC-EQ IF  2DROP TSRC-UDOTR TRUE EXIT  THEN
  2DUP S" HEX" TSRC-EQ IF  2DROP 16 TSRC-STORE-BASE TRUE EXIT  THEN
  2DUP S" DECIMAL" TSRC-EQ IF  2DROP 10 TSRC-STORE-BASE TRUE EXIT  THEN
  2DUP S" STACK-HUD" TSRC-EQ IF  2DROP S" STACKHUD#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" 0=" TSRC-EQ IF  2DROP S" ZEQ#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" =" TSRC-EQ IF  2DROP S" EQ#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" <>" TSRC-EQ IF  2DROP S" NEQ#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" <" TSRC-EQ IF  2DROP S" LT#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" >" TSRC-EQ IF  2DROP S" GT#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" ROT" TSRC-EQ IF  2DROP S" ROT#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" NIP" TSRC-EQ IF  2DROP S" NIP#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" 2DUP" TSRC-EQ IF  2DROP S" 2DUP#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" S>N" TSRC-EQ IF  2DROP S" SNUMBER#" TSRC-LIB-CALL TRUE EXIT  THEN
  2DUP S" ARGCOUNT" TSRC-EQ IF  2DROP S" ARGCOUNT" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" ARG1" TSRC-EQ IF  2DROP S" ARG1" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" ARG2" TSRC-EQ IF  2DROP S" ARG2" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" ARG#" TSRC-EQ IF  2DROP S" ARG#" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP TSRC-SQUOT? IF  2DROP TSRC-COMPILE-STRING TRUE EXIT  THEN
  2DUP TSRC-DOTQUOT? IF
    2DROP TSRC-COMPILE-STRING S" TYPE#" TSRC-LIB-CALL TRUE EXIT
  THEN
  2DROP FALSE
  ;

\ CASE OF ENDOF ENDCASE — nested IF/ELSE chain
\ (Uses SYM-FIND/COMP-CALL directly so this can be defined before TSRC-LIB-CALL is used.)
VARIABLE #CASE-OF
: (CASE-CALL)  ( ca u -- )
  2DUP SYM-FIND IF  >R 2DROP R> SYM-ADDR@ COMP-CALL
  ELSE  TYPE S"  missing for CASE" TCOM-ABORT  THEN
  ;
: TCASE  ( -- )  0 #CASE-OF ! ;
\ ANS-compatible CASE (same as 64Forth / ANS Core Ext):
\   OF:     OVER = IF DROP   (selector consumed on match)
\   ENDOF:  ELSE
\   ENDCASE: DROP then resolve THENs
\ Match paths skip the ENDCASE DROP via ELSE…THEN; the default arm
\ must NOT DROP the selector (ENDCASE does that).
: TOF  ( -- )
  S" OVER#" (CASE-CALL)
  S" EQ#"   (CASE-CALL)
  TIF
  S" DROP#" (CASE-CALL)
  1 #CASE-OF +!
  ;
: TENDOF  ( -- )  TELSE ;
: TENDCASE  ( -- )
  S" DROP#" (CASE-CALL)              \ ANS: drop selector (default / fall-through)
  BEGIN #CASE-OF @ WHILE  TTHEN  -1 #CASE-OF +!  REPEAT
  ;

: TSRC-CTRL?  ( ca u -- f )
  2DUP S" IF" TSRC-EQ IF  2DROP S" TIF" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" ELSE" TSRC-EQ IF  2DROP S" TELSE" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" THEN" TSRC-EQ IF  2DROP S" TTHEN" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" BEGIN" TSRC-EQ IF  2DROP S" TBEGIN" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" UNTIL" TSRC-EQ IF  2DROP S" TUNTIL" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" AGAIN" TSRC-EQ IF  2DROP S" TAGAIN" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" WHILE" TSRC-EQ IF  2DROP S" TWHILE" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" REPEAT" TSRC-EQ IF  2DROP S" TREPEAT" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" DO" TSRC-EQ IF  2DROP S" TDO" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" ?DO" TSRC-EQ IF  2DROP S" TQDO" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" LOOP" TSRC-EQ IF  2DROP S" TLOOP" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" +LOOP" TSRC-EQ IF  2DROP S" T+LOOP" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" LEAVE" TSRC-EQ IF  2DROP S" TLEAVE" TSRC-HOST-EXEC TRUE EXIT  THEN
  2DUP S" CASE" TSRC-EQ IF  2DROP TCASE TRUE EXIT  THEN
  2DUP S" OF" TSRC-EQ IF  2DROP TOF TRUE EXIT  THEN
  2DUP S" ENDOF" TSRC-EQ IF  2DROP TENDOF TRUE EXIT  THEN
  2DUP S" ENDCASE" TSRC-EQ IF  2DROP TENDCASE TRUE EXIT  THEN
  2DROP FALSE
  ;

: TSRC-BRACKET-OP  ( ca u -- )
  2DUP S" CHAR" TSRC-EQ IF
    2DROP TSRC-TOKEN DUP 0= IF  2DROP S" CHAR needs a character" TSRC-ERR  THEN
    DROP C@ EXIT
  THEN
  TSRC-HOST-EXEC
  ;

: TSRC-POSTPONE  ( -- )
  TSRC-IN-COLON @ 0= IF  S" POSTPONE outside :" TSRC-ERR  THEN
  TSRC-TOKEN DUP 0= IF  2DROP S" POSTPONE needs a name" TSRC-ERR  THEN
  2DUP PAD PLACE
  TSRC-CTRL? IF  EXIT  THEN
  PAD COUNT TSRC-PRIM? IF  EXIT  THEN
  PAD COUNT SYM-FIND IF
    DUP SYM-TYPE@ SYM-DEFINER = IF  DROP S" POSTPONE defining word" TSRC-ERR  THEN
    DUP SYM-IMM? IF  TSRC-RUN-IMM  ELSE  SYM-COMPILE-REF  THEN
  ELSE
    PAD COUNT TYPE S"  ?" TSRC-ERR
  THEN
  ;

: (TSRC-DISPATCH)  ( ca u -- )
  DUP 0= IF  2DROP EXIT  THEN

  TSRC-BRACKET @ IF
    2DUP S" ]" TSRC-EQ IF  2DROP TSRC-RBRACK EXIT  THEN
    2DUP TSRC->NUMBER IF  NIP NIP EXIT  THEN
    TSRC-BRACKET-OP EXIT
  THEN

  TSRC-SKIP-CT @ IF
    2DUP S" DOES>" TSRC-EQ IF  2DROP TSRC-DOES> EXIT  THEN
    2DUP S" ;" TSRC-EQ IF  2DROP TSRC-SEMI EXIT  THEN
    2DROP EXIT
  THEN

  2DUP S" VARIABLE" TSRC-EQ IF
    2DROP TSRC-TOKEN DUP 0= IF  2DROP S" VARIABLE needs a name" TSRC-ERR  THEN
    TSRC-VARIABLE EXIT
  THEN
  2DUP S" CREATE" TSRC-EQ IF
    2DROP
    TSRC-IN-COLON @ IF
      TSRC-MARK-DEFINER
    ELSE
      TSRC-TOKEN DUP 0= IF  2DROP S" CREATE needs a name" TSRC-ERR  THEN
      TSRC-CREATE DROP
    THEN
    EXIT
  THEN
  2DUP S" CONSTANT" TSRC-EQ IF
    2DROP TSRC-TOKEN DUP 0= IF  2DROP S" CONSTANT needs a name" TSRC-ERR  THEN
    TSRC-CONSTANT EXIT
  THEN
  2DUP S" :NONAME" TSRC-EQ IF  2DROP TSRC-NONAME-START EXIT  THEN
  2DUP S" IMMEDIATE" TSRC-EQ IF  2DROP TSRC-IMMEDIATE EXIT  THEN
  2DUP S" DOES>" TSRC-EQ IF  2DROP TSRC-DOES> EXIT  THEN
  2DUP S" [" TSRC-EQ IF  2DROP TSRC-LBRACK EXIT  THEN
  2DUP S" ]" TSRC-EQ IF  2DROP TSRC-RBRACK EXIT  THEN
  2DUP S" LITERAL" TSRC-EQ IF  2DROP TSRC-LITERAL EXIT  THEN
  2DUP S" POSTPONE" TSRC-EQ IF  2DROP TSRC-POSTPONE EXIT  THEN
  2DUP S" RECURSE" TSRC-EQ IF  2DROP TSRC-RECURSE EXIT  THEN
  2DUP S" VOCABULARY" TSRC-EQ IF
    2DROP TSRC-TOKEN DUP 0= IF  2DROP S" VOCABULARY needs a name" TSRC-ERR  THEN
    TSRC-VOCABULARY EXIT
  THEN
  2DUP S" ALSO" TSRC-EQ IF  2DROP TSRC-ALSO EXIT  THEN
  2DUP S" ONLY" TSRC-EQ IF  2DROP TSRC-ONLY EXIT  THEN
  2DUP S" DEFINITIONS" TSRC-EQ IF  2DROP TSRC-DEFINITIONS EXIT  THEN
  2DUP S" FORTH" TSRC-EQ IF  2DROP TSRC-FORTH EXIT  THEN
  2DUP S" '" TSRC-EQ IF  2DROP TSRC-TICK EXIT  THEN
  2DUP S" VALUE" TSRC-EQ IF
    2DROP TSRC-TOKEN DUP 0= IF  2DROP S" VALUE needs a name" TSRC-ERR  THEN
    TSRC-VALUE EXIT
  THEN
  2DUP S" :" TSRC-EQ IF
    2DROP TSRC-TOKEN DUP 0= IF  2DROP S" : needs a name" TSRC-ERR  THEN
    TSRC-COLON EXIT
  THEN
  2DUP S" ;" TSRC-EQ IF  2DROP TSRC-SEMI EXIT  THEN
  2DUP S" FLOAD" TSRC-EQ IF  2DROP TSRC-DO-FLOAD EXIT  THEN
  2DUP S" INCLUDE" TSRC-EQ IF  2DROP TSRC-DO-FLOAD EXIT  THEN
  2DUP S" ," TSRC-EQ IF  2DROP TSRC-COMMA EXIT  THEN
  2DUP S" ALLOT" TSRC-EQ IF  2DROP TSRC-ALLOT EXIT  THEN
  2DUP S" CELLS" TSRC-EQ IF
    2DROP
    TSRC-IN-COLON @ IF
      S" CELLS#" TSRC-LIB-CALL
    ELSE
      DEPTH 0= IF  S" CELLS underflow" TSRC-ERR  THEN
      8 *
    THEN
    EXIT
  THEN
  2DUP S" TO" TSRC-EQ IF  2DROP TSRC-TO EXIT  THEN
  2DUP S" =:" TSRC-EQ IF  2DROP TSRC-TO EXIT  THEN
  2DUP S" !>" TSRC-EQ IF  2DROP TSRC-TO EXIT  THEN
  2DUP S" OFF>" TSRC-EQ IF  2DROP 0 G, TSRC-TO EXIT  THEN
  2DUP S" ON>" TSRC-EQ IF  2DROP -1 G, TSRC-TO EXIT  THEN
  2DUP S" +!>" TSRC-EQ IF  2DROP TSRC-+TO EXIT  THEN
  \ ?EXIT ( flag -- )  EXIT if flag nonzero (ANS). Was wrongly ZEQ-inverted.
  2DUP S" ?EXIT" TSRC-EQ IF
    2DROP S" TIF" TSRC-HOST-EXEC
    S" RET," TSRC-HOST-EXEC S" TTHEN" TSRC-HOST-EXEC EXIT
  THEN
  2DUP TSRC-CTRL? IF  EXIT  THEN

  TSRC-IN-COLON @ 0= IF
    \ top-level number → host stack (for , VALUE ALLOT CELLS)
    2DUP TSRC->NUMBER IF
      NIP NIP EXIT                     \ ( ca u n true ) → n
    THEN
    2DUP SYM-FIND IF
      NIP NIP
      DUP SYM-TYPE@ SYM-DEFINER = IF  TSRC-RUN-DEFINER EXIT  THEN
      DUP SYM-TYPE@ SYM-VOCAB = IF  TSRC-SET-WID EXIT  THEN
      TYPE S"  at top level (use inside :)" TSRC-ERR
    THEN
    TYPE S"  at top level (VARIABLE CREATE VALUE CONSTANT : FLOAD ALLOT , CELLS)" TSRC-ERR
  THEN

  2DUP TSRC-PRIM? IF  EXIT  THEN

  \ Number inside :
  2DUP TSRC->NUMBER IF
    NIP NIP G, EXIT
  THEN

  2DUP SYM-FIND IF
    NIP NIP
    DUP SYM-TYPE@ SYM-DEFINER = IF  DROP S" defining word inside :" TSRC-ERR  THEN
    DUP SYM-IMM? IF  TSRC-RUN-IMM  ELSE  SYM-COMPILE-REF  THEN
  ELSE
    TYPE S"  ?" TSRC-ERR
  THEN
  ;
' (TSRC-DISPATCH) IS TSRC-DISPATCH

: TSRC-LAST-SLASH  ( c-addr u -- n )
  -1 TSRC-ACC !
  0 TSRC-BASE !
  BEGIN TSRC-BASE @ OVER < WHILE
    OVER TSRC-BASE @ + C@ [CHAR] / = IF TSRC-BASE @ TSRC-ACC ! THEN
    1 TSRC-BASE +!
  REPEAT
  2DROP TSRC-ACC @
  ;

: TSRC-SET-CUR-PATH  ( c-addr u -- )
  250 UMIN 2DUP TSRC-CUR-PATH PLACE
  2DUP TSRC-LAST-SLASH
  DUP 0< IF
    DROP 2DROP
    0 TSRC-CUR-DIR C!
  ELSE
    NIP 1+ TSRC-CUR-DIR PLACE
  THEN
  ;

\ ( ca u -- ca' u' ) resolve relative to TSRC-CUR-DIR into TSRC-RESOLVED
: TSRC-RESOLVE  ( c-addr u -- c-addr2 u2 )
  DUP 0= IF EXIT THEN
  OVER C@ [CHAR] / = IF
    250 UMIN TSRC-RESOLVED PLACE  TSRC-RESOLVED COUNT EXIT
  THEN
  TSRC-CUR-DIR C@ 0= IF
    250 UMIN TSRC-RESOLVED PLACE  TSRC-RESOLVED COUNT EXIT
  THEN
  TSRC-CUR-DIR COUNT TSRC-RESOLVED PLACE
  ( path-ca path-u )
  DUP TSRC-RESOLVED C@ + 250 > IF
    2DROP S" TSRC path too long" TSRC-ERR
  THEN
  TSRC-RESOLVED COUNT +          ( path-ca path-u dest )
  OVER TSRC-RESOLVED C@ + TSRC-RESOLVED C!
  SWAP MOVE
  TSRC-RESOLVED COUNT
  ;

: TSRC-NEST-PATH-A  ( idx -- ca )  256 * TSRC-NEST-PATH + ;
: TSRC-NEST-DIR-A   ( idx -- ca )  256 * TSRC-NEST-DIR + ;
: TSRC-NEST-BUF-A   ( idx -- ca )  CELLS TSRC-NEST-BA + @ ;

: TSRC-STATE-SAVE  ( idx -- )
  >R
  TSRC-LEN  @  R@ CELLS TSRC-NEST-LEN  + !
  TSRC-I    @  R@ CELLS TSRC-NEST-I    + !
  TSRC-LINE @  R@ CELLS TSRC-NEST-LINE + !
  TSRC-CUR-PATH COUNT  R@ TSRC-NEST-PATH-A PLACE
  TSRC-CUR-DIR  COUNT  R@ TSRC-NEST-DIR-A  PLACE
  R@ TSRC-LEN @ TSRC-NEST-ENSURE
  TSRC-BUF  R@ TSRC-NEST-BUF-A  TSRC-LEN @ MOVE
  R> DROP
  ;

: TSRC-STATE-RESTORE  ( idx -- )
  >R
  R@ CELLS TSRC-NEST-LEN  + @ TSRC-LEN  !
  R@ CELLS TSRC-NEST-I    + @ TSRC-I    !
  R@ CELLS TSRC-NEST-LINE + @ TSRC-LINE !
  R@ TSRC-NEST-PATH-A COUNT TSRC-CUR-PATH PLACE
  R@ TSRC-NEST-DIR-A  COUNT TSRC-CUR-DIR  PLACE
  TSRC-LEN @ TSRC-ENSURE-CAP
  R@ TSRC-NEST-BUF-A  TSRC-BUF  TSRC-LEN @ MOVE
  R> DROP
  ;

\ Load entire file into TSRC-BUF. Sizes from FILE-SIZE (grows past 64 KiB);
\ grows further while reading if needed. Never silently truncates.
: TSRC-LOAD-FILE  ( ca u -- )
  R/O OPEN-FILE IF
    DROP TYPE S" : can't open source" TSRC-ERR
  THEN
  TSRC-FID !
  TSRC-FID @ FILE-SIZE IF
    2DROP
    /TSRC-BUF-MIN TSRC-ENSURE-CAP
    -1 TSRC-NEED !
  ELSE
    ( lo hi )
    IF
      DROP TSRC-FID @ CLOSE-FILE DROP
      S" TSRC: file too large (>4GiB)" TSRC-ERR
    THEN
    DUP TSRC-NEED !
    TSRC-ENSURE-CAP
  THEN
  0 TSRC-LEN !
  BEGIN
    /TSRC-BUF TSRC-LEN @ - DUP 0= IF
      DROP
      TSRC-GROW
      /TSRC-BUF TSRC-LEN @ -
    THEN
    TSRC-BUF TSRC-LEN @ +  SWAP
    TSRC-FID @ READ-FILE
    IF
      TSRC-FID @ CLOSE-FILE DROP
      S" read error" TSRC-ERR
    THEN
    DUP 0= IF
      DROP
      TSRC-NEED @ 0< 0= IF
        TSRC-LEN @ TSRC-NEED @ <> IF
          TSRC-FID @ CLOSE-FILE DROP
          S" TSRC: short read (size mismatch)" TSRC-ERR
        THEN
      THEN
      TSRC-FID @ CLOSE-FILE DROP EXIT
    THEN
    TSRC-LEN +!
  AGAIN
  ;

: TSRC-RUN  ( -- )
  0 TSRC-I !
  1 TSRC-LINE !
  FALSE TSRC-IN-COLON !
  FALSE TSRC-BRACKET !
  FALSE TSRC-SKIP-CT !
  FALSE TSRC-DEFINER !
  FALSE TSRC-IN-DOES !
  FALSE TSRC-NONAME !
  TSRC-DEPTH @ 1 = IF  0 TSRC-CTP !  THEN
  BEGIN
    TSRC-TOKEN                     \ ( ca u )
    DUP 0= IF
      2DROP
      TSRC-IN-COLON @ IF  S" unclosed : at EOF" TSRC-ERR  THEN
      EXIT
    THEN
    TSRC-DISPATCH                  \ consumes ( ca u )
  AGAIN
  ;

: TSRC-INCLUDE  ( ca u -- )
  TSRC-DEPTH @ #TSRC-NEST U>= IF
    2DROP S" TSRC FLOAD nesting too deep" TSRC-ERR
  THEN
  TSRC-DEPTH @ IF
    TSRC-DEPTH @ 1- TSRC-STATE-SAVE
  ELSE
    \ Top-level path is cwd-relative as given (TCOM-CLI samples/foo.fth)
    0 TSRC-CUR-DIR C!
  THEN
  1 TSRC-DEPTH +!
  TSRC-RESOLVE                   \ nested relative names use CUR-DIR
  ?QUIET 0= IF  2DUP TYPE S"  (TSRC)" TYPE CR  THEN
  2DUP TSRC-SET-CUR-PATH
  TSRC-LOAD-FILE
  TSRC-RUN
  -1 TSRC-DEPTH +!
  TSRC-DEPTH @ IF
    TSRC-DEPTH @ 1- TSRC-STATE-RESTORE
  ELSE
    TSRC-BUILD-FIND-TABLE
  THEN
  ;

: TSRC-INCLUDE"  ( -- )
  TSRC-QUOT-CH PARSE TSRC-INCLUDE
  ;

\ Path after FLOAD/INCLUDE: bare token or "quoted"
: TSRC-PARSE-PATH  ( -- ca u )
  TSRC-SKIP-WS
  TSRC-EOF? IF  S" FLOAD needs a filename" TSRC-ERR  THEN
  TSRC-PEEK TSRC-QUOT-CH = IF
    TSRC-GETC DROP
    TSRC-I @ >R
    BEGIN
      TSRC-GETC DUP 0< IF  DROP R> DROP S" unclosed FLOAD path" TSRC-ERR  THEN
      TSRC-QUOT-CH = IF
        TSRC-BUF R@ +  TSRC-I @ 1- R@ -  R> DROP  EXIT
      THEN
    AGAIN
  THEN
  TSRC-TOKEN
  DUP 0= IF  2DROP S" FLOAD needs a filename" TSRC-ERR  THEN
  ;

: TSRC-FLOAD  ( -- )
  TSRC-IN-COLON @ IF  S" FLOAD inside :" TSRC-ERR  THEN
  TSRC-PARSE-PATH
  TSRC-INCLUDE
  ;
' TSRC-FLOAD IS TSRC-DO-FLOAD

: .64SRC  ( -- )
  S" 64SRC — restricted .fth loader (compiler, pack-independent)" TYPE CR
  S"   c-addr u TSRC-INCLUDE   FLOAD/INCLUDE inside .fth" TYPE CR
  S"   Comments: \\ line  ( )  \\ ... {  or  } ... {" TYPE CR
  S"   Buffer: 64 KiB min, grows to FILE-SIZE (cap 16 MiB)" TYPE CR
  S"   Needs pack: TIF TELSE TTHEN … G@ G! prims" TYPE CR
  ;

FORTH DEFINITIONS
S" 64SRC loaded (TSRC-INCLUDE)." TYPE CR
